### ISSUE TITLE
Using embedded-consul behind a corporate http proxy

### ISSUE THREAD

**Issue by mv200580** [pszymczyk/embedded-consul#19]
When using embedded-consul behind a corporate http proxy, I'm getting next error:

```
16:05:02.403 [main] INFO com.pszymczyk.consul.ConsulStarter - Starting new Consul process.
16:05:03.419 [main] INFO com.pszymczyk.consul.ConsulStarter - Downloading archives into: C:\Users\smv\AppData\Local\Temp\embedded-consul\consul.zip
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 2.025 sec <<< FAILURE! - in com.litmusloop.loopmq.auth.SuperuserControllerTest
com.litmusloop.loopmq.auth.SuperuserControllerTest  Time elapsed: 2.025 sec  <<< ERROR!
java.net.ConnectException: Connection refused: connect
	at java.net.DualStackPlainSocketImpl.connect0(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:79)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:668)
	at sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:173)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
...
```

**Comment by pszymczyk** [comment]
Hi

It looks like problem with downloading Consul binaries, embedded-consul downloads binaries from:
`https://releases.hashicorp.com/consul/${version}/consul_${version}_${os}_amd64.zi`
Try to download Consul from this link on your corporate machine.

**Comment by mv200580** [comment]
I can download Consul by the browser with proxy settings, but the problem that I can't find the way to specify the proxy setting for embedded-consul. Is it possible to get the proxy setting from the environment variable, for example, HTTP_PROXY ?
Or maybe even better decision - check if consul zip already downloaded in destination directory and use it instead of downloading. So it would be possible to download consul zip manually.

**Comment by mv200580** [comment]
I solved the problem by specifying VM options -Dhttps.proxyHost=... -Dhttps.proxyPort=... for IDE JUnit run configuration and for maven-surefire-plugin configuration.
But still thinking that it will be useful to check local version instead of the downloading the new consul archive every time when tests run. It will reduce the run time of the tests.

**Comment by pszymczyk** [comment]
Archive isn't downloading every time, it's described in `Files structure` section: https://github.com/pszymczyk/embedded-consul#files-structure

`To avoid unnecessary downloads Consul binary is downloaded into static named directory /$tmp/embedded-consul. `

you can specify `$tmp` path by `ConsulBuilder`
