### ISSUE TITLE
javax.net.ssl.SSLHandshakeException when downloading Consul

### ISSUE THREAD

**Issue by johnboy14** [pszymczyk/embedded-consul#27]
I am getting the following error when attempting to download the Consul client for embedded use.  I am not sure if this is a proxy related issue.  I can download the artifact despite this fact but when I specify a binary directory, the code tries to overwrite it anyway.  W

```
@Before
public void setUp() throws Exception {

        consul = ConsulStarterBuilder.consulStarter()
                .withHttpPort(8080)
                .build()
                .start();
        client = Consul.builder().build();
    }

```
```
2016-11-14T16:08:46.702+0000 INFO [Seq=1,Log=Thread=main] org.slf4j.Logger$info:? Starting new Consul process.
2016-11-14T16:08:46.724+0000 INFO [Seq=2,Log=,Thread=main] org.slf4j.Logger$info$0:? Downloading archives into: /var/folders/q2/5pyc9lwx77v80zk351v6lns0w8pvsj/T/embedded-consul/consul.zip

Disconnected from the target VM, address: '127.0.0.1:56162', transport: 'socket'
javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

	at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
	at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1949)
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:302)
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:296)
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1509)
	at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:216)
	at sun.security.ssl.Handshaker.processLoop(Handshaker.java:979)
	at sun.security.ssl.Handshaker.process_record(Handshaker.java:914)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1062)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1375)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1403)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1387)
	at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1546)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
	at java.net.URL.openStream(URL.java:1045)
	at java_net_URL$openStream.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:117)
	at com.pszymczyk.consul.infrastructure.HttpBinaryRepository.getConsulBinaryArchive(HttpBinaryRepository.groovy:9)
	at com.pszymczyk.consul.infrastructure.HttpBinaryRepository$getConsulBinaryArchive.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:133)
	at com.pszymczyk.consul.ConsulStarter.downloadAndUnpackBinary(ConsulStarter.groovy:135)
	at com.pszymczyk.consul.ConsulStarter.start(ConsulStarter.groovy:82)`

```

**Comment by pszymczyk** [comment]
Hi

I think I can expose consul binary location, so you could set your internal package repository, eg:

```
consul = ConsulStarterBuilder.consulStarter().withBinaryUrl("http://your-local-resource-location")
```

instead of default `"https://releases.hashicorp.com/consul/${version}/consul_${version}_${os}_amd64.zip"`

**Comment by pszymczyk** [comment]
@johnboy14 It helps you? Can I close this issue?
