### ISSUE TITLE
Consul port on separate hosts can't run?

### ISSUE THREAD

**Issue by hugadams** [pszymczyk/embedded-consul#58]
https://github.com/pszymczyk/embedded-consul/blob/ca80e661cd1c22dec9e9aa0c706bea2298ad81ec/src/main/groovy/com/pszymczyk/consul/ConsulStarter.groovy#L155

Sorry to open two issues, please close if I'm off base.  

Using the consul CLI, I can run two agents locally as long as they are bound to different addresses.  

```
consul agent -server -bind=127.0.0.1 -client=127.0.0.1 -datacenter=tpc
consul agent -server -bind=127.0.0.2 -client=127.0.0.2 -datacenter=cnj

```

However, a corresponding consulConfig will get trapped on the above line.  It seems like it only checks ports of the agent, instead of the socket address.  Thus agents running on 127.0.0.1 and 127.0.0.2 cannot co-exist.

```
com.pszymczyk.consul.EmbeddedConsulException: Port 8500 is not available, cannot start Consul process.

	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:83)
	at org.codehaus.groovy.reflection.CachedConstructor.doConstructorInvoke(CachedConstructor.java:77)
	at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrap.callConstructor(ConstructorSite.java:84)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:60)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:235)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:247)
	at com.pszymczyk.consul.ConsulStarter$_checkInitialState_closure2.doCall(ConsulStarter.groovy:156)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:294)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1024)
	at groovy.lang.Closure.call(Closure.java:414)
	at groovy.lang.Closure.call(Closure.java:430)
	at org.codehaus.groovy.runtime.IOGroovyMethods.withCloseable(IOGroovyMethods.java:1622)
	at org.codehaus.groovy.runtime.IOGroovyMethods$withCloseable.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:133)
	at com.pszymczyk.consul.ConsulStarter.checkInitialState(ConsulStarter.groovy:155)
	at com.pszymczyk.consul.ConsulStarter.start(ConsulStarter.groovy:94)
	at com.bnymellon.tsg.discovery.tests.cucumber.consul.EmbeddedConsulAgent.start(EmbeddedConsulAgent.java:40)
	at com.bnymellon.tsg.discovery.tests.cucumber.consul.ConsulAgentManager.setup(ConsulAgentManager.java:31)
	at com.bnymellon.tsg.discovery.tests.cucumber.consul.ConsulIntegrationStepDefs.setupConsulFromFile(ConsulIntegrationStepDefs.java:81)
	at ✽.consul agents two-datacenters-wan.json(src/test/resources/TestRegistration.feature:8)

```

**Comment by hugadams** [comment]
Wow, thanks!  I will go ahead and clone the fixed version and confirm my problem is solved.  Right now our project is using maven central to get embedded consul.  Will change project to pull from github after branch is merged.  Any idea what typical release cycle for this project is, out of curiosit?

**Comment by pszymczyk** [comment]
@hugadams release is not a problem, it's stil manual process unfortunately but I can make it any time :)

**Comment by pszymczyk** [comment]
@hugadams release is not a problem, it's stil manual process unfortunately but I can make it any time :)

**Comment by hugadams** [comment]
Thanks  @pszymczyk 

Do you guys have any recommended way to point a maven project to a git branch?  I was going to follow a solution here: https://stackoverflow.com/questions/20161602/loading-maven-dependencies-from-github but it looks like I have to provide a release tag.  If you guys cut a release, can you let me know on these comments if you think about it?  I'll keep checking back.

Very nice project by the way, thanks!

**Comment by ruslansennov** [comment]
@pszymczyk @hugadams 
I believe we can release new version right after merging last two PRs

**Comment by hugadams** [comment]
Awesome, thanks.  PS I closed by accident, so am reopening.  Feel free to close at your discretion.

**Comment by hugadams** [comment]
@ruslansennov Thanks, I saw the consul version was merged and updated to 1.1.0.  Do you have a recommended way to get the latest artifact?  Would a site like maven repository get updated within say a week, or is it best for me to clone and build locally?

**Comment by pszymczyk** [comment]
@shortstories @ruslansennov thanks for contribution, change is released in 1.1.0 which should be in mvn central in few hours :)

**Comment by pszymczyk** [comment]
http://repo1.maven.org/maven2/com/pszymczyk/consul/embedded-consul/1.1.0/

**Comment by hugadams** [comment]
Thanks!

**Comment by hugadams** [comment]
@pszymczyk  @ruslansennov 

I think there still may be a bug in ConsulStarter.  When running two agents on separate addresses but on the same port, this line will think they are the same address.

            IOGroovyMethods.withCloseable(new Socket("localhost", consulPorts.httpPort), {

For example, 127.0.0.1:8500 and 127.0.0.2:8500

For now, working around by using separate ports.

**Comment by ruslansennov** [comment]
> For example, 127.0.0.1:8500 and 127.0.0.2:8500

Oh, my tests use addresses other than localhost, my bad. It seems that replacing `"localhost"` to `bind ?: "localhost"` solves the problem
